In [5]:
import numpy as np

In [6]:
# Create a 2x3x4 array (2 layers, 3 rows, 4 columns)
array_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("Shape:", array_3d.shape)  # (2, 3, 4)
print("\nFirst layer:\n", array_3d[0])
print("\nElement at position [1,2,3]:", array_3d[1,2,3])  # 24



Shape: (2, 3, 4)

First layer:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at position [1,2,3]: 24


In [7]:
# Basic operations
print("\nSum of all elements:", array_3d.sum())
print("Mean value:", array_3d.mean())




Sum of all elements: 300
Mean value: 12.5


In [8]:
# Accessing slices
print("\nFirst row of second layer:", array_3d[1,0])
print("Middle column of all layers:\n", array_3d[:,:,1])


First row of second layer: [13 14 15 16]
Middle column of all layers:
 [[ 2  6 10]
 [14 18 22]]
