### Random Number Generators
NumPy uses pseudo-random number generators (PRNGs) that produce sequences of numbers that appear random but are actually deterministic when given a starting point (the seed).

In [13]:
import numpy as np

In [14]:
# Set a seed for reproducibility
np.random.seed(42)

In [15]:
np.random.random()           # Single random float between 0 and 1

0.3745401188473625

In [16]:
np.random.random(5)         # Array of 5 random floats

array([0.95071431, 0.73199394, 0.59865848, 0.15601864, 0.15599452])

In [17]:
np.random.random((3, 3))        # 3x3 array of random floats

array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

### Sampling

In [18]:
# Create a sample dataset
data = np.arange(100)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


When replace=True (the default):

An item can be selected multiple times
The same value may appear repeatedly in your sample
Each selection is independent of previous selections
The probability of selecting any item remains constant throughout the sampling process

In [19]:
# Random choice with replacement
samples1 = np.random.choice(data, size=20) # Choose 10 items
samples2 = np.random.choice(data, size=20) # Choose 10 items
samples3 = np.random.choice(data, size=20) # Choose 10 items
print(samples1)
print(samples2)
print(samples3)

[20 32 75 57 21 88 48 90 58 41 91 59 79 14 61 61 46 61 50 54]
[63  2 50  6 20 72 38 17  3 88 59 13  8 89 52  1 83 91 59 70]
[43  7 46 34 77 80 35 49  3  1  5 53  3 53 92 62 17 89 43 33]


When replace=False:

Once an item is selected, it cannot be selected again
Each value in the result will be unique
The sample size must be less than or equal to the population size
The probability of selecting remaining items increases with each selection

In [20]:
# Random choice without replacement
samples4 = les = np.random.choice(data, size=10, replace=False)  # 10 unique items

# Weighted random sampling
weights = np.linspace(1, 10, 100)                                # Increasing weights
np.random.choice(data, size=50, p=weights/weights.sum())

array([62, 89, 92,  3, 68, 61, 42, 29, 54, 96, 52, 69, 82, 56, 98, 97, 45,
       67, 50, 49, 13, 76, 68, 16, 48, 94, 44, 32, 67, 99, 44, 80, 86, 44,
       83, 57, 77, 77, 70, 24, 90, 52, 38, 14, 74, 80,  7, 68, 42, 78])