### Simple broadcasting

In [23]:
import numpy as np


In [24]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [25]:
# Simplest case: same shape
res = a * b
print('Shape: ', res.shape, ' ndim: ', res.ndim)
print('Result: ', res)

Shape:  (3,)  ndim:  1
Result:  [2. 4. 6.]


In [26]:
# Array and num:
num = 4.0
res = a * num
print('Shape: ', res.shape)
print('Result: ', res)

Shape:  (3,)
Result:  [ 4.  8. 12.]


### More complex
Number of dimensions is not the same.  
Case 1: Shapes values are the same (right to left) but ndim is not)

In [27]:
arr1 = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
arr2 = np.ones(6, dtype=np.int64).reshape(2,3) 
print('arr1 shape: ', arr1.shape)
print('arr2 shape: ', arr2.shape)
print(arr2)

arr1 shape:  (4, 2, 3)
arr2 shape:  (2, 3)
[[1 1 1]
 [1 1 1]]


In [28]:
res = arr1 + arr2
print('res sahpe: ', res.shape)
print(res)

res sahpe:  (4, 2, 3)
[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]

 [[24 25 26]
  [27 28 29]]]


Case 2: Values are NOT the same (right to left) but not-equal value is ONE:

In [29]:
arr1 = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
arr2 = np.ones(3, dtype=np.int64).reshape(1,3) 
print('arr1 shape: ', arr1.shape)
print('arr2 shape: ', arr2.shape)
print(arr2)

arr1 shape:  (4, 2, 3)
arr2 shape:  (1, 3)
[[1 1 1]]


In [30]:
res = arr1 + arr2
print('res sahpe: ', res.shape)
print(res)

res sahpe:  (4, 2, 3)
[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]

 [[24 25 26]
  [27 28 29]]]


In [35]:
arr1 = np.array([[1], [2], [3], [4]])
arr2 = np.array([[100, 200, 300]])
print('shape: ', arr1.shape)
print('shape: ', arr2.shape)

shape:  (4, 1)
shape:  (1, 3)


In [36]:
res = arr1 + arr2
print('shape: ', res.shape)
print(res)

shape:  (4, 3)
[[101 201 301]
 [102 202 302]
 [103 203 303]
 [104 204 304]]
