In [20]:
import numpy as np

## Single element indexing

In [21]:
arr = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
print('3d:\n', arr, ' shape: ', arr.shape)

3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[23 24 25]
  [26 27 28]]]  shape:  (4, 2, 3)


In [22]:
arr[2]

array([[13, 14, 15],
       [16, 17, 18]])

..then a 2d array:

In [23]:
arr[2, 0]

array([13, 14, 15])

In [27]:
# You can also use this syntax:
# Note that it is inefficient, because a temporary array object is created
arr[2][0]

array([13, 14, 15])

In [24]:
arr[2,0,1]

np.int64(14)

## Boolean indexing

In [25]:
# Creating a mask
mask = ((arr % 2) == 0)
print('mask: \n', mask)

mask: 
 [[[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]]


In [26]:
# Boolean indexing
arr[mask]     # [4 5 6]
print('arr[mask]:\n', arr[mask])

arr[mask]:
 [ 2  4  6  8 10 12 14 16 18 24 26 28]
