In [4]:
import numpy as np

In [5]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [6]:
a + b         # [5 7 9]


array([5, 7, 9])

In [7]:
a * b         # [4 10 18]


array([ 4, 10, 18])

In [8]:
a ** 2        # [1 4 9]



array([1, 4, 9])

In [9]:
# Broadcasting
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr + 1       # adds 1 to each element

array([[2, 3, 4],
       [5, 6, 7]])