In [36]:
import numpy as np

## Single element indexing

In [37]:
arr = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
print('3d:\n', arr, '\nshape: ', arr.shape, '\nndim: ', arr.ndim )

3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[23 24 25]
  [26 27 28]]] 
shape:  (4, 2, 3) 
ndim:  3


In [38]:
arr[2]

array([[13, 14, 15],
       [16, 17, 18]])

..then a 2d array:

In [39]:
arr[2, 0]   # Note that this is not like indexing in a 2d "list of lists" in Python

array([13, 14, 15])

In [40]:
# You can also use this syntax (the old Python way):
# Note that it is inefficient, because a temporary array object is created:
#    first arr[2],  then index that again 
arr[2][0]

array([13, 14, 15])

In [41]:
# 3d indexing:
arr[2,0,1]

np.int64(14)

## Boolean indexing

In [42]:
# Creating a mask
mask = ((arr % 2) == 0)
print('mask: \n', mask)

mask: 
 [[[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]]


In [43]:
# Boolean indexing
arr[mask]     # [4 5 6]
print('arr[mask]:\n', arr[mask])

arr[mask]:
 [ 2  4  6  8 10 12 14 16 18 24 26 28]


In [ ]:
# or boolean index directly:
arr[(arr%2) == 0]

Note that NumPy boolean indexing flattens the result, you loose the original shape.   
If you want to preseve it you can use [np.where()](https://numpy.org/doc/2.2/reference/generated/numpy.where.html#numpy-where)
(note: the documentation is not very clear there)

In [ ]:
np.where( (arr % 2) == 0,  arr,  '***')

# Explanations:
#   First expression is the array I want to afect
#   Second - is a broadcastable to that shape, that says what to put in the result if condition is True
#   Third - is a broadcastable to that shape, that says what to put in the result if condition is NOT True