In [1]:
import numpy as np

In [2]:
arr = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
print('3d:\n', arr, ' shape: ', arr.shape)

3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[23 24 25]
  [26 27 28]]]  shape:  (4, 2, 3)


### Ellipsis
Expands to the number of : objects needed for the selection tuple to index all dimensions

In [3]:
#This...
arr[...,0]

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [23, 26]])

In [4]:
# Is equivalent to this:
arr[:, :, 0]

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [23, 26]])

### np.newaxis
np.newaxis is a special object in NumPy used to increase the dimensionality of an array by adding a new axis (dimension) of length 1

In [5]:
arr = np.array([1, 2, 3, 4])
print("Original array shape:", arr.shape)  # (4,)

# Add new axis at the end (make it a column vector)
col_vector = arr[:, np.newaxis]
print("Column vector shape:", col_vector.shape)  # (4, 1)

Original array shape: (4,)
Column vector shape: (4, 1)


In [6]:
# Add new axis at the beginning (make it a row vector)
row_vector = arr[np.newaxis, :]
print("Row vector shape:", row_vector.shape)  # (1, 4)


Row vector shape: (1, 4)


In [9]:
# Alternative syntax using None
# These are equivalent to using np.newaxis
col_vector_alt = arr[:, None]
row_vector_alt = arr[None, :]
print(col_vector_alt.shape)
print(row_vector_alt.shape)

(4, 1)
(1, 4)


In [13]:
x = np.arange(5)
A = x[:, np.newaxis]
y = np.arange(5)
B = x[np.newaxis, :]
print(A)
print(B)
print(A+B)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
