In [53]:
import numpy as np

### Basic slicing

In [54]:
arr = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
print('3d:\n', arr, ' shape: ', arr.shape)

3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[23 24 25]
  [26 27 28]]]  shape:  (4, 2, 3)


## Slicing

In [55]:
arr[:, 0, 0]   # Column 1

array([ 1,  7, 13, 23])

In [56]:
arr[0:2, 1:, :2]  # Rows 0-1, array 1 (and on), column 0-1


array([[[ 4,  5]],

       [[10, 11]]])

In [57]:
# Still, the slice is not a copy
arr[0:2, 1:, :2].base is arr

True

In [58]:
# If the number of slices are less tham the number of dimensions:
print(arr[0:2])         # option 1
print(arr[0:2, :, :])   # option 2 - the same 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [59]:
print(arr[0:2].shape)

(2, 2, 3)


In [60]:
arr[:, 0:1, :].shape

(4, 1, 3)

### Setting values with slices
- You may use slicing to set values in the array
- Unlike lists, you can never grow the array
- The size of the value to be set in the slice, must be (broadcastable to) the same shape as the slice.

In [61]:
someslice = arr[0:2, 0:2, 2:]
arr[0:2, 0:2, 2:] = np.array([101,102,103,104]).reshape(someslice.shape)
arr

array([[[  1,   2, 101],
        [  4,   5, 102]],

       [[  7,   8, 103],
        [ 10,  11, 104]],

       [[ 13,  14,  15],
        [ 16,  17,  18]],

       [[ 23,  24,  25],
        [ 26,  27,  28]]])