In [14]:
import numpy as np
import pandas as pd

### Basic example

In [15]:
# Create a sample array
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [16]:
# Boolean indexing creates a mask of True/False values
greater_than_five = numbers > 5
greater_than_five

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [17]:
# Use the mask to filter the array
result = numbers[greater_than_five]
result

array([ 6,  7,  8,  9, 10])

### Using boolean operators

In [18]:
# Multiple conditions using & (and) or | (or)
mask = (numbers > 3) & (numbers < 8)
mask

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [19]:
numbers[mask]  # Returns [4, 5, 6, 7]

array([4, 5, 6, 7])

### An example with DataFeame

In [20]:
# Common use case with Pandas DataFrame
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 28],
    'score': [85, 92, 78, 95]
})


In [21]:
# Filter DataFrame for people over 28 with scores above 80
filtered_df = df[(df['age'] > 28) & (df['score'] > 80)]
filtered_df

name  age  score
1  Bob   30     92