In [37]:
import numpy as np

# From Python list
np.array([1, 2, 3])


array([1, 2, 3])

In [38]:
# Built-in methods
np.zeros(6)         # [0. 0. 0. 0. 0.]

array([0., 0., 0., 0., 0., 0.])

In [39]:
np.ones((2, 3))      # 2x3 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.arange(0, 10, 2)  # [0 2 4 6 8]

array([0, 2, 4, 6, 8])

In [41]:
np.linspace(0, 1, 5)  # 5 evenly spaced numbers

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
# Random arrays
np.random.rand(3, 3)  # 3x3 random matrix


array([[0.1414581 , 0.44097483, 0.50947354],
       [0.92010111, 0.30859599, 0.62995363],
       [0.92346838, 0.07436637, 0.32369682]])