In [11]:
import numpy as np

In [12]:
# Creating 2D arrays
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print('simple 2d:\n', array_2d)

simple 2d:
 [[1 2 3]
 [4 5 6]]


In [13]:
# From range
array_range = np.array([range(3), range(3, 6)])  # [[0,1,2], [3,4,5]]
print('simple 2d from ranges:\n', array_range)

simple 2d from ranges:
 [[0 1 2]
 [3 4 5]]


In [14]:
# Using reshape
array_flat = np.arange(6)  # [0,1,2,3,4,5]
array_2d = array_flat.reshape(2, 3)  # [[0,1,2], [3,4,5]]
print('reshape: flat:', array_flat)
print('reshape: 2d \n', array_2d)

reshape: flat: [0 1 2 3 4 5]
reshape: 2d 
 [[0 1 2]
 [3 4 5]]


In [15]:
# Common patterns
zeros_2d = np.zeros((2, 3))    # [[0,0,0], [0,0,0]]
print('zeros:\n', zeros_2d)

ones_2d = np.ones((2, 3))      # [[1,1,1], [1,1,1]]
print('ones:\n', ones_2d)

identity = np.eye(3)           # 3x3 identity matrix
print('eye:\n', identity)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
