### [reshape documentation](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape)

In [36]:
import numpy as np

In [37]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [38]:
arr.reshape(4)      # Flatten to 1D

array([1, 2, 3, 4])

In [39]:
# Use -1 so that you do not have to calculate the lebgth yourself
arr.reshape(-1)

array([1, 2, 3, 4])

In [40]:
arr.reshape(1, 4)   # Reshape to different 2D

array([[1, 2, 3, 4]])

In [41]:
# This will not work:
arr.reshape(5)

ValueError: cannot reshape array of size 4 into shape (5,)