In [11]:
import numpy as np

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr:\n', arr)
print('shape: ', arr.shape)

arr:
 [[1 2 3]
 [4 5 6]]
shape:  (2, 3)


In [13]:
# Transpose
arrT = arr.T
print('transpose:\n', arrT)
print('shape: ', arrT.shape)

transpose:
 [[1 4]
 [2 5]
 [3 6]]
shape:  (3, 2)
