In [1]:
import numpy as np

Used to create an array filled with 111.. or 000...

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

**By default:**

np.zeros() returns float64: np.zeros(3)  # [0. 0. 0.]  
np.ones() returns float64: np.ones(3)  # [1. 1. 1.]  

But you can specify a type

In [4]:
np.zeros(3, dtype=int)     # [0 0 0]


array([0, 0, 0])

In [5]:
np.ones(3, dtype=np.int8)  # [1 1 1]

array([1, 1, 1], dtype=int8)